id: I84B9AD3A
legacy_id: P009455
ocr_import_info:
  bdrc_scan_id: W1CZ1179
  source: bdrc
  ocr_info:
    timestamp: '2020-03-27T11:02:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T18:58:54.340487+00:00'
last_modified: 2022-08-31 02:59:04.448825
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ1179
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ1179
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: རྗེས་སུ་རྣལ་འབྱོར།
statistics:
  ocr_word_mean_confidence_index: 0.522315436514757
  ocr_word_median_confidence_index: 0.47999998927116394
quality: null
bases:
  I1CZ1630:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ1630
      total_pages: 44
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ1630.txt
    statistics:
      ocr_word_median_confidence_index: 0.47999998927116394
      ocr_word_mean_confidence_index: 0.522315436514757
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
