id: I84B9AD3A
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T11:02:34+00:00'
last_modified: '2022-06-08T11:09:52.193108+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ1179
  title: རྗེས་སུ་རྣལ་འབྱོར་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    F728:
      image_group_id: I1CZ1630
      title: ''
      total_pages: 44
      order: 1
      base_file: F728.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
