id: P009455
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ1179
  title: རྗེས་སུ་རྣལ་འབྱོར་
  author: ''
  volumes:
    c914077011dd40bd895503d096d8d461:
      image_group_id: I1CZ1630
      title: ''
      volume_number: 1
      total_pages: 44
      base_file: v001.txt
