id: P009455
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 19:39:36.005146
source_metadata:
  id: bdr:W1CZ1179
  title: རྗེས་སུ་རྣལ་འབྱོར་
  author: ''
  volumes:
    c914077011dd40bd895503d096d8d461:
      image_group_id: I1CZ1630
      title: ''
      volume_number: 1
      total_pages: 44
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
